version: '3.4'
services:
  golang:
    image: flemay/golang:1.9.2-stretch
    volumes:
      - .:/go/src/github.com/flemay/3musketeers/examples/lambda-go-serverless
    working_dir: /go/src/github.com/flemay/3musketeers/examples/lambda-go-serverless

  serverless:
    image: amaysim/serverless:1.25.0
    env_file: .env
    volumes:
      - ~/.aws:/root/.aws
      - .:/opt/app
    working_dir: /opt/app