service: the3musketeers-lambdagosls
package:
  artifact: package.zip
provider:
  name: aws
  runtime: go1.x
  region: ${env:AWS_REGION}
  stage: ${env:ENV}

functions:
  echo:
    handler: bin/main
    description: returns the value of environment variable ECHO_MESSAGE
    memorySize: 128
    environment:
      ECHO_MESSAGE: ${env:ECHO_MESSAGE}
    events:
      - http:
          path: echo
          method: get